In [1]:
import numpy as np
A=np.array([[1,2,3],[3,4,5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [2]:
array =np.zeros((2,3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
x = 1
while x <= 10:
    if x % 2==1:
        print(f'Odd: {x}')
    else:
        print(f'Even: {x}')
    x += 1

Odd: 1
Even: 2
Odd: 3
Even: 4
Odd: 5
Even: 6
Odd: 7
Even: 8
Odd: 9
Even: 10
